### ISSUE TITLE
Are some files missing?

### ISSUE THREAD

**Issue by iSach** [giulio98/functional-diffusion-processes#1]
Hello,

I am going through your paper and code to run it on new datasets. First of all, I sincerely thank you for releasing such a clean repository with detailed instructions. This is much appreciated and sadly too rare in academia.

I am trying to go through the examples given in the README file. However, it seems like some files are maybe missing?

* In `sdetools`, the init file mentions `.vp_sde import VPSDE`, but there is no `vp_sde.py` file.
* In `scripts/maml`, there should be a `train_mnist.sh` but there is none. Only eval, sample, and run (is run the correct one maybe?)

I have not gone through the rest yet due to that. 

Thanks in advance,
Sacha Lewin.

**Comment by giulio98** [comment]
Dear Sacha Lewin,

Thank you for your kind words and for bringing these issues to our attention.

You are correct in your observations. The missing files you mentioned were intentionally left out in our last refactoring. To address this, I have recently made a commit that should resolve these issues. Specifically, the VPSDE file was not included because it was integrated into our codebase during a debugging phase. For a detailed understanding of the VPSDE implementation, you might find the repository at https://github.com/yang-song/score_sde insightful.

Our code is intentionally designed to be modular, facilitating the easy implementation of new SDEs. Should you encounter any further difficulties or have additional questions, please do not hesitate to open another issue. Alternatively, feel free to open a pull request. I would be more than happy to review and merge your contributions.

Best regards,

Giulio Corallo.

**Comment by iSach** [comment]
> Dear Sacha Lewin,
> 
> Thank you for your kind words and for bringing these issues to our attention.
> 
> You are correct in your observations. The missing files you mentioned were intentionally left out in our last refactoring. To address this, I have recently made a commit that should resolve these issues. Specifically, the VPSDE file was not included because it was integrated into our codebase during a debugging phase. For a detailed understanding of the VPSDE implementation, you might find the repository at https://github.com/yang-song/score_sde insightful.
> 
> Our code is intentionally designed to be modular, facilitating the easy implementation of new SDEs. Should you encounter any further difficulties or have additional questions, please do not hesitate to open another issue. Alternatively, feel free to open a pull request. I would be more than happy to review and merge your contributions.
> 
> Best regards,
> 
> Giulio Corallo.

Dear Giulio Corallo,

Thanks a lot for this fast and complete reply! I will definitely dive into it deeper and will open PRs if I have something new that works! :) 

Best regards,
Sacha Lewin.
