### ISSUE TITLE
wandb:do not have permission to access the requested resource

### ISSUE THREAD

**Issue by ghost** [giulio98/functional-diffusion-processes#4]
Hi . I met a new issue.  Do i need you pemission for wandb or i miss something >.<
Thank you!

wandb: Currently logged in as: zxcvzxcv980234. Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: entity your_entity not found during upsertBucket (<Response [404]>)
Problem at: /cis/net/io93c/data/shuan124/functional-diffusion-processes/src/functional_diffusion_processes/trainers/trainer.py 93 initialize_wandb
wandb: ERROR It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Error executing job with overrides: ['+experiments_maml=exp_mnist']

**Comment by giulio98** [comment]
Hey there!

I wanted to start by mentioning that in our config file, we've left a placeholder for the wandb entity because we don't know your actual entity name. 

The error you're encountering is because this placeholder needs to be updated with your specific wandb username or organization name.
Here's how you can sort it out:
* First off, you'll need to update `you_entity` with your actual wandb entity name when running your script. Your command should look something like this:
```
PYTHONPATH=. python3 src/functional_diffusion_processes/run.py --multirun +experiments_maml=exp_mnist \
trainers.trainer_logging.wandb_init.project="fdp_mnist" \
trainers.trainer_logging.wandb_init.entity="<your_wandb_entity_name>"
```
Just swap `<your_wandb_entity_name>` with your actual entity name.

OR
* If you prefer using a config file, just update the entity and project fields in `conf/trainers/trainer_maml.yaml` with your details. Then run the script as is.

OR
* If you don't want to log with wandb: you can skip it entirely by setting use_wandb=False in your command:
```
PYTHONPATH=. python3 src/functional_diffusion_processes/run.py --multirun +experiments_maml=exp_mnist \
trainers.trainer_logging.use_wandb=False
```
Hope it helps!

**Comment by ghost** [comment]
i run it successfully !! thank you so much !!
